server:
  port: 8088
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: WorkingHoursApp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    sql-script-encoding: UTF-8
  h2:
    console.enabled: true
    console.path: /h2
logging:
  level:
    com.chubby.demo: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true

com:
  chubby:
    #start work 8:00 am
    start-work: 8
    #end work 16:00 pm
    end-work: 16
    #one day max work hour
    max-work-hour: 8